@Certify
Feature: Certify token

    Background:
        * url karate.properties['baseUrl']
        * def dataGenerator = Java.type('Divoc.utils.DataGenerator')
        * def randomNumber = dataGenerator.generateRandomNumber()
        * def result = call read('classpath:Divoc/authentication/CreateAuthToken.feature')
        * def authToken = result.response.access_token

    Scenario Outline:  <Description>


        * text certifyToken =
            """
            [
                {
                    "preEnrollmentCode": "<randomNumber>",
                    "recipient": {
                        "name": "<Name>",
                        "dob": "<DOB>",
                        "gender": "<Gender>",
                        "nationality": "<Nationality>",
                        "identity": "<Identity>",
                        "contact": [
                            "tel:<MobileNumber>"
                        ],
                        "address": {
                            "addressLine1": "<AddressLine1>",
                            "addressLine2": "<AddressLine2>",
                            "district": "<District>",
                            "state": "<State>",
                            "pincode": "<pincode>"
                        }
                    },
                    "vaccination": {
                        "name": "<VaccineName>",
                        "batch": "<Batch>",
                        "manufacturer": "<Manufacturer>",
                        "date": "<Date>",
                        "effectiveStart": "<StartDate>",
                        "effectiveUntil": "<EndDate>",
                        "dose": <Dose>,
                        "totalDoses": <TotalDose>
                    },
                    "vaccinator": {
                        "name": "<VaccinatorName>"
                    },
                    "facility": {
                        "name": "<FacilityName>",
                        "address": {
                            "addressLine1": "<FacilityAddressLine1>",
                            "addressLine2": "<FacilityAddressLine1>",
                            "district": "<FacilityDistrict>",
                            "state": "<FacilityState>",
                            "pincode": "<FacilityPincode>"
                        }
                    }
                }
            ]
            """
        * def requestPayload = JSON.parse(certifyToken)

        Given url baseUrl
        And path "/divoc/api/v1/certify"
        And replace requestPayload.randomNumber = randomNumber
        * def requestPayload = JSON.parse(requestPayload)
        And header Authorization = 'Bearer '+ authToken
        And request requestPayload
        When method post
        Then status <status>
        * print response


        Given url baseUrl
        And path "/cert/api/certificatePDF/"+randomNumber
        And header Authorization = 'Bearer '+ authToken
        When method get
        Then status 200
        * print response


        Examples:
            | Description                                                                                            | status | Name          | DOB        | Gender    | Nationality | Identity                    | MobileNumber     | AddressLine1                                                                                                          | AddressLine2                                                                                                          | District         | State     | Pincode       | VaccineName    | Batch         | Manufacturer        | Date                    | StartDate  | EndDate    | Dose       | TotalDose  | VaccinatorName    | FacilityName             | FacilityAddressLine1                                                                           | FacilityAddressLine2                                                                                                                            | FacilityDistrict | FacilityState | FacilityPincode |
            | Certification for status 200                                                                           | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for Name with special character                                                          | 200    | Megha Jain#&* | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for future dates                                                                         | 200    | Megha Jain    | 2050-11-03 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid DOB with special charater                                                    | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100abc  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for Driving license with alpha numeric values                                            | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100abc  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for Driving license with alphabets                                                       | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:sdfabc  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for driving license with alpha-numeric values and special character                      | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:1!@0abc | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for district-state mismatch                                                              | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Ernakulam        | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for   District with number                                                               | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South1 | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for District with alphanumeric values and special character                              | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | @!dD232          | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for state that includes alphanumeric values and special character                        | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | 121da1!@!!#      | !223@#@s  | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for vaccine name that includes alphanumeric values and special character                 | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN@@!!s11 | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for vaccine name that includes space in between                                          | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN 1      | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for Batch with includes alphanumeric values and special character                        | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX!@##  | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification  for Batch with space in between                                                         | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX QW28 | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for future Date                                                                          | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2050-11-03T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for start date with invalid Date                                                         | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2050-11-03 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for end date with invalid Date                                                           | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2050-11-03 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for end Date  with alpha-numeric value and special character                             | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh@@ += | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for vaccinator with special character                                                    | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC12 Medical Center     | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for facility name with numeric value                                                     | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh 12   | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for vaccinator with numeric character                                                    | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical@@! Center1+G | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for vaccinator with special character                                                    | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Ernakulam        | Karnataka     | 560034          |
            | Certification for facility district-state mismatch                                                     | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru South1 | Karnataka     | 560034          |
            | certification for facility District with number                                                        | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | @!dD232          | Karnataka     | 560034          |
            | Certification for facility District with alphanumeric values and special character                     | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | 121da1!@!!#      | !223@#@s      | 560034          |
            | Certification for  faciliyy state and district that includes alphanumeric values and special character | 200    | Megha Jain    | 1983-01-30 | Male      | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for gender as male                                                                       | 200    | Megha Jain    | 1983-01-30 | Others    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | Certification for gender as Others                                                                     | 200    | Megha Jain    | 1983-01-30 | Others    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for Gender value others                                                                  | 200    | Megha Jain    | 1983-01-30 | 123456    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for numeric value as gender                                                              | 200    | Megha Jain    | 1983-01-30 | 123Gender | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for alhpanumeric vaue as gender                                                          | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 909090909        | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for phone number with limit less than 10                                                 | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 90909090908908   | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for phone number with limit >10                                                          | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | mobilenumbertest | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for phone number with alphabets as value                                                 | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar, $#%@.                                                                                                 | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for adress line1 with special characters                                                 | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar, Jayanagar, Jayanagar, Jayanagar,Jayanagar,Jayanagar,Jayanagar,Jayanagar,Jayanagar,Jayanagar,Jayanagar | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for long address line1                                                                   | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross , 4th cross, 4th cross, 4th cross, 4th cross, 4th cross, 4th cross,4th cross, 4th cross,4th cross,4th cross | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for long address line2                                                                   | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross, %$^#&*                                                                                                     | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for adress line2 with special characters                                                 | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 5601234567024 | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for pin code greter than 6                                                               | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | testpincode   | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for pin code with alphabets values                                                       | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech_&%^* | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for  total Dose with alphbet values                                                      | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 10         | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for  total Dose with value >2                                                            | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala, Koramangala, Koramangala, Koramangala, Koramangala, Koramangala, Koramangala | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for facility adress line1 with special characters                                        | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala , %^&**(*)                                                                    | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for long facility address line1                                                          | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross , 3rd Cross , 3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross ,3rd Cross | Bengaluru        | Karnataka     | 560034          |
            | certification for long facility address line2                                                          | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross   &*&*&*&*()$%%                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for facility adress line2 with special characters                                        | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 56003490909     |
            | certification for facility pin code >6                                                                 | 200    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | Testpincode     |


    Scenario Outline:  <Description>


        * text certifyToken =
            """
            [
                {
                    "preEnrollmentCode": "<randomNumber>",
                    "recipient": {
                        "name": "<Name>",
                        "dob": "<DOB>",
                        "gender": "<Gender>",
                        "nationality": "<Nationality>",
                        "identity": "<Identity>",
                        "contact": [
                            "tel:<MobileNumber>"
                        ],
                        "address": {
                            "addressLine1": "<AddressLine1>",
                            "addressLine2": "<AddressLine2>",
                            "district": "<District>",
                            "state": "<State>",
                            "pincode": "<pincode>"
                        }
                    },
                    "vaccination": {
                        "name": "<VaccineName>",
                        "batch": "<Batch>",
                        "manufacturer": "<Manufacturer>",
                        "date": "<Date>",
                        "effectiveStart": "<StartDate>",
                        "effectiveUntil": "<EndDate>",
                        "dose": <Dose>,
                        "totalDoses": <TotalDose>
                    },
                    "vaccinator": {
                        "name": "<VaccinatorName>"
                    },
                    "facility": {
                        "name": "<FacilityName>",
                        "address": {
                            "addressLine1": "<FacilityAddressLine1>",
                            "addressLine2": "<FacilityAddressLine1>",
                            "district": "<FacilityDistrict>",
                            "state": "<FacilityState>",
                            "pincode": "<FacilityPincode>"
                        }
                    }
                }
            ]
            """
        * def requestPayload = JSON.parse(certifyToken)

        Given url baseUrl
        And path "/divoc/api/v1/certify"
        And replace requestPayload.randomNumber = randomNumber
        * def requestPayload = JSON.parse(requestPayload)
        And header Authorization = 'Bearer '+ authToken
        And request requestPayload
        When method post
        Then status <status>
        * print response


        Examples:



            | Description                                                                  | status | Name       | DOB        | Gender | Nationality | Identity                   | MobileNumber | AddressLine1   | AddressLine2 | District        | State     | Pincode | VaccineName | Batch    | Manufacturer   | Date                    | StartDate  | EndDate    | Dose | TotalDose | VaccinatorName | FacilityName       | FacilityAddressLine1 | FacilityAddressLine2 | FacilityDistrict | FacilityState | FacilityPincode |
            | Certification for invalid DOB                                                | 400    | Megha Jain | 1983-13-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | certification for invalid date in DOB                                        | 400    | Megha Jain | 2003-02-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for DOB with alphabet                                          | 400    | Megha Jain | yyyy-mm-dd | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid date and month in DOB                              | 400    | Megha Jain | @#$%-0@-q! | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for Date with alphabet                                         | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | yyyy-mm-ddT19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid Date                                               | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 1983-13-30:21:19.646    | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid information in Date                                | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2003-02-30T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid date value  Date                                   | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2003-04-31T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid month value  Date                                  | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | !@#$-0@-3dT19:21:19.646 | 2020-12-15 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for Date  with alpha-numeric value and special character       | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | yyyy-mm-dd | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for start date with alphabet                                   | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 1983-13-30 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for start date with future Date                                | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2003-02-30 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid information in Start date                          | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2003-04-31 | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid month value  in Start Date                         | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | !@#$-0@-3d | 2021-01-15 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for Start Date  with alpha-numeric value and special character | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | yyyy-mm-dd | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for end date with alphabet                                     | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | 1983-13-30 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for end date with future Date                                  | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | 2003-02-30 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid information in end date                            | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | 2003-04-31 | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | Certification for invalid month value  in end Date                           | 400    | Megha Jain | 1983-01-30 | Female | Indian      | did:Driving License:100126 | 9090909090   | 123, Jayanagar | 4th cross    | Bengaluru South | Karnataka | 560024  | COVAXIN     | MB3428BX | Bharat Biotech | 2020-03-24T19:21:19.646 | 2020-12-15 | !@#$-0@-3d | 1    | 2         | Sooraj Singh   | ABC Medical Center | 123, Koramangala     | 3rd Cross            | Bengaluru        | Karnataka     | 560034          |
            | certification for manufacturer with special character                        | 400    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | "Testdose" | 2          | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
            | certification for Dose with alphbet values                                   | 400    | Megha Jain    | 1983-01-30 | Female    | Indian      | did:Driving License:100126  | 9090909090       | 123, Jayanagar                                                                                                        | 4th cross                                                                                                             | Bengaluru South  | Karnataka | 560024        | COVAXIN        | MB3428BX      | Bharat Biotech      | 2020-03-24T19:21:19.646 | 2020-12-15 | 2021-01-15 | 1          | "TestDose" | Sooraj Singh      | ABC Medical Center       | 123, Koramangala                                                                               | 3rd Cross                                                                                                                                       | Bengaluru        | Karnataka     | 560034          |
