name: Docker Image CI

on:
  push:
    branches: [ main]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ main, orchestration ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: mvn test -Dtest=CertifyAPIRunner.java  -DfailIfNoTests=false
    
